// <auto-generated />
using System;
using GameDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameDemo.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20191217100754_ChangedResultTable")]
    partial class ChangedResultTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameDemo.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Move");

                    b.Property<string>("PlayerName");

                    b.Property<int>("WinCount");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameDemo.Models.Result", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("CurrentTurn");

                    b.Property<string>("GameResult");

                    b.Property<int>("Player1Move");

                    b.Property<int>("Player2Move");

                    b.Property<string>("PlayerMove");

                    b.Property<string>("PlayerName");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
